config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

   get '/about' => 'pages#about'
   get '/contact' => 'pages#contact'
   get '/portfolio' => 'pages#portfolio'
   get '/resume' => 'pages#resume'
   
   resources :articles 
   
   
   get 'search_articles', to: 'articles#search'
   
   
   get '/signup' => 'users#new'
   resources :users, except: [:new]
   
   get 'login' => 'sessions#new'
   post 'login' => 'sessions#create'
   delete 'logout' => 'sessions#destroy'
   

end

app/models/article.rb
class Article < ActiveRecord::Base
    belongs_to :user
    validates :title, presence: true, length: { minimum: 3}
    validates :description, presence: true, length: { minimum: 3} 
    validates :date, presence: true
    validates :user_id, presence: true
    
    
    def self.search(param)
        return Article.none if param.blank?
        param.strip!
        param.downcase!
        (title_matches(param) + tags_matches(param)).uniq
    end
    
    def self.title_matches(param)
        matches('title', param)
    end
    
    def self.tags_matches(param)
        matches('tags', param)
    end
    
    def self.matches(field_name, param)
        where("lower(#{field_name}) like ?", "%#{param}%")
    end
   
end 

app/models/user.rb
class User < ActiveRecord::Base
    has_many :articles 
    validates :username, presence: true 
    has_secure_password

end  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id] 
  end 
  
  def logged_in?
    !!current_user 
  end
  
  def require_user
    if !logged_in?
      flash[:danger] = "You must log in to do that."
      redirect_to root_path
    end 
  end 
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:edit, :update, :show, :destroy] 
    before_action :require_user, except: [:index, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]
   
    def index
        @articles = Article.paginate(page: params[:page], per_page: 5)
    end 
    
    def new 
        @article = Article.new 
    end 
    
    def edit
        
    end 
    
    
    def update
        
        if @article.update(article_params)
            flash[:success] = "Post was successfully updated!"
            redirect_to article_path(@article)
        else 
            render 'edit'
        end 
    end 
    
    def create
        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save
           flash[:success] = "Post was successfully created!" 
           redirect_to article_path(@article)
        else
            render 'new'
        end 
    end 
    
    def show
        
    end 
    
    def searchPage
       
    end
    
    
    def destroy
        
        @article.destroy
        flash[:danger] = "Post was deleted!"
        redirect_to articles_path 
    end 
    
    def search
        @articles = Article.search(params[:search_param])
        
        if @articles
            render partial: 'lookup'
        else
            render status: :not_found, nothing: true
        end
    end 
    
    private
        def set_article
          @article = Article.find(params[:id])  
        end
        
        def require_same_user
            if current_user != @article.user and !current_user.admin?
                flash[:danger] = "You can only edit or delete your own posts."
                redirect_to root_path
            end
        end 
        
        def article_params
                params.require(:article).permit(:title, :description, :date, :tags)
        end 
    
end 

app/controllers/pages_controller.rb
class PagesController < ApplicationController 
    def home
    
    end 
    def about
        
    end 
    def contact
    
    end 
    def portfolio
        
    end 
    def resume 
        
    end 
end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def new 
        
    end 
    
    def create
        user = User.find_by(username: params[:session] [:username])
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
           flash[:success] = "You are now logged in." 
           redirect_to articles_path
        else 
            flash.now[:danger] = "Your username and/or password were incorrect."
            render 'new'
        end 
    end 
    
    def destroy
        session[:user_id] = nil
        flash[:success] = "You have been logged out."
        redirect_to root_path
    end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def new 
        @user = User.new
    end 
    
    def create
        @user = User.new(user_params)
        if @user.save
            flash[:success] = "You have been signed up!"
            redirect_to articles_path
        else 
            render 'new'
        end 
    end

    private
        def user_params
            params.require(:user).permit(:username, :password)
        end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_editDelete.html.erb
<% if logged_in? && (current_user == @article.user || current_user.admin?)%>
        <button class="btn btn-default">
            <%= link_to "Edit Post", edit_article_path %> 
        </button>
        <button class="btn btn-default">
            <%= link_to "Delete Post", article_path(@article), :method => :delete, data: {confirm: "Are you sure?"} %>
        </button>
<% end %>

app/views/articles/_form.html.erb
<button>
    <%= link_to "Back to Blog", articles_path %> 
</button>
<br>
<br>
<% if @article.errors.any? %>
<div id="error" class="alert alert-danger">
<ul>
    <a href="#" class="close" data-dismiss="alert">&#215;</a>
    <h4>There were errors with your blog post:</h4>
    <% @article.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
</ul> 
</div>
<% end %>

<%= form_for @article do |f| %> 

    <div>
        Title:<%= f.text_field :title %>
    </div> <br>
    <div>
        Date: <%= f.date_field :date? %>
    </div><br>
    <div>
        Tags: <%= f.text_field :tags %> 
    </div>
    <div>
        <p>Post:</p>
        <%= f.text_area :description, id:'blogArea' %>
    </div>
    
    <div>
        <%= f.submit "Post Blog" %>
    </div>

<% end %> 

app/views/articles/_indexPaginate.html.erb
<div>
     <%= will_paginate %>
</div>
<div>
                    
        <% @articles.each do |article| %> 
        <div class="post">
            <h2><%= article.title %></h2>
            <div>
                <p><%= article.date %></p>
            </div>
            <div>
                <pre><%= truncate(article.description.html_safe, length: 75) %>
                <%= link_to " Continue Reading ->", article_path(article) %></pre>
            </div>
        
            <div class="tagDiv">
                Tagged with: <%= article.tags %> 
            </div>
            
        </div>
        <% end %>
                
</div>
<div>
    <%= will_paginate %>
</div>

app/views/articles/_lookup.html.erb
<div id="article-lookup">
    <%= form_tag search_articles_path, remote: true, method: :get, id: 'article-lookup-form' do %>
        <div class="form-group row no-padding text-center col-md-12">
            <div class="col-md-10">
                <%= text_field_tag :search_param, params[:search_param], placeholder: 'Search by Title or Tag',
                        autofocus: true, class: 'form-control search-box input-lg' %>
            </div>
            <div class="col-md-2">
                <%= button_tag(type: :submit, class: 'btn btn-xs btn-default') do %>
                <i class='fa fa-search'></i> Look up an article
                <% end %>
            </div>
        </div>
        <% end %>
    
    <%= render 'articles/spinner' %>
        <% if params[:search_param].blank? %>
           
        <% else %>
        <h3>Search Results</h3>
            <% if @articles.size > 0 %> 
            <div id="article-lookup-results" class="well results-block col-md-10">
                <table class="search-results-table col-md-12">
                    <tbody>
                        <% @articles.each do |article| %>
                        <tr>
                            <td><strong>Title:</strong> <%= article.title %></td>
                            <td><strong>Tags:</strong><%= article.tags %></td>
                            <td><strong><%= link_to "Read Post", article_path(article) %></strong></td>
                        </tr>
                        <% end %>
                    </tbody>
                </table> 
            </div>
           <% else %>
            <p class="lead col-md-12">
                No posts meet this search criteria.
            </p>
            <% end %>
        <% end %>
            
<div id="article-lookup-errors"></div>
</div>

app/views/articles/_newPostLinkIndex.html.erb
<% if logged_in? %>
    <header class = "">
        <div class = ""> 
            <button class="btn btn-default">
                <%= link_to "Create New Post", new_article_path %>
            </button>
        </div>
    </header>
<% end %>

app/views/articles/_searchLink.html.erb
<header class = "">
        <div class = ""> 
            <button class="btn btn-default">
                <%= link_to "Search for Posts", searchPage_articles_path %>
            </button>
        </div>
</header>

app/views/articles/_spinner.html.erb
<div id="spinner" class="row col-md-12 text-center spinner" style="display:none;">
    <i class="fa fa-spinner fa-spin fa-2x"></i> Processing...
</div>

app/views/articles/edit.html.erb
<div id="edit" class="sectionDiv">
<div class="sectionTitle">Edit Blog Entry</div>
<hr class="sectionHR">

<%= render 'form' %>

</div>

app/views/articles/index.html.erb
<div id="blog" class="sectionDiv">
        <div class="sectionTitle">Blog</div>
        <hr class="sectionHR">
        
        <%= render 'lookup' %>
        <div>
            <%= render 'newPostLinkIndex' %>
            
            <%= render 'indexPaginate' %>
        </div>

</div> 

app/views/articles/new.html.erb
<div id="newBlog" class="sectionDiv">
<div class="sectionTitle">Add A New Blog</div>
<hr class="sectionHR">

<%= render 'form' %>

</div> 

app/views/articles/searchPage.html.erb
<%= render 'lookup' %>

app/views/articles/show.hmtl.erb
<%= render "partials/header" %>

<div id="show" class="sectionDiv">
<div class="sectionTitle"></div>
<hr class="sectionHR">

     <div class ="">
                    <div class ="">
                        <div>
                            <h4><a>blogTitle</a></h4>
                            <p>blogDate</p>
                            <div id="postArea"><pre id="postedBlog">blogPost</pre></div>
                            <button class="btn"><a href="/blogs/<%=blog._id%>/edit">Edit</a></button>
                            <form id="" action="/blogs/<%=blog._id%>?_method=DELETE" method="POST">
                                <button class="btn">Delete</button>
                            </form>
                        </div>
                    </div>
        </div>

</div>

<%= render "partials/footer" %>

app/views/articles/show.html.erb
<div id="show" class="sectionDiv">
<div class="sectionTitle"></div>
<hr class="sectionHR">
    <button class="btn btn-default">
        <%= link_to "Back to Blog", articles_path %> 
    </button>
    <br>
    <br>
     <div class ="">
                    <div class ="">
                        <div>
                            <h2><%= @article.title %></h2>
                            <%= @article.date %>
                            <hr class="showHR">
                            <div><%= simple_format(@article.description.html_safe) %></div>
                            <div>
                                Tags: <%= @article.tags %> 
                            </div><br>
                            <%= render 'editDelete' %>
                        </div>
                    </div>
        </div>

</div>

app/views/layouts/_blurb.html.erb
            <div id="blurb" class="sectionDiv">
                 <%= image_tag("cara.jpg", :alt => "cara") %>
                <p class="nameBlurb">Cara J. Suppa</p>
                <hr class="sectionHR">
                <p>Freelance writer, glorious/low-brow foodie and recent iPhone convert. 
                Witness my effort to rein in an almost debilitating tendency toward sarcasm 
                and self-deprecation.</p>
                  <%= render 'layouts/logoutButton' %>
            </div>

       

app/views/layouts/_header.html.erb
<div class="container">
     <div id="headTitle">Cara J. Suppa: The Online Writing Portfolio</div>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/">Home <span class="sr-only">(current)</span></a></li>
        <li><a href="/about">About</a></li>
        <li><a href="/portfolio">Portfolio</a></li>
        <li><a href="/resume">Resumé</a></li>
        <li><a href="/contact">Contact</a></li>
        <li><a href="/articles">Blog</a></li>
      </ul>
      <ul class="nav navbar-right">
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</div>

app/views/layouts/_logoutButton.html.erb
<% if logged_in? %>
    <button class="btn btn-default">
        <%= link_to 'log out', logout_path, method: :delete %>
    </button>
<% end %>

app/views/layouts/_messages.html.erb
      <% flash.each do |name,msg| %>
         <div class='alert alert-<%= "#{name}"%>'>
            <a href="#" class="close" data-dismiss="alert">&#215;</a>
            <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
         </div>
      <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cara J. Suppa: The Online Writing Portfolio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
</head>
<body>
<%= render 'layouts/messages' %>
 <%= render 'layouts/header' %>
 <%= render 'layouts/blurb' %>
 
 <%= yield %>

</body>
</html>

app/views/pages/about.html.erb
 <div id="about" class="sectionDiv">
    <div class="sectionTitle">ABOUT</div>
    <hr class="sectionHR"/>
    <table>
        <tr>
            <td>
                <%= image_tag("caraAndDog.jpg", :alt => "caraDog", :id => "caraDog") %>
                <div>Just a typical day at the office.</div>
            </td>
        </tr>
    </table>
    <p>You can read all about my academic background in the resume section, 
    but what it doesn’t tell you is that — like so many before me — I failed at college 
    the first time around for sheer lack of focus. When I went back full-time in earnest, 
    I had switched majors from history to writing and suddenly found myself immersed in 
    the company of a group of peers who were whip-smart and devastatingly sarcastic and who — 
    just by being part of my everyday life — challenged me to do better and try harder than I had before.</p>
    
    <p>I also wrote under an incredible cache of professors who encouraged me and 
    made me believe in my talent. Failing out of college is humiliating; these teachers 
    gave me the self-confidence I needed to excel, while helping me find my calling, my purpose.</p>
    
    <p>Since graduating in 2010 with high honors, I have been working mainly as a 
    freelance writer, penning web content on a regular basis and long fiction pieces 
    on a more sporadic schedule, both as a ghost writer (hence my lack of links-to-articles). 
    Before I started I wondered if it was like working in fast food, where you sometimes 
    develop an aversion to cheeseburgers. (I mean, I could never not love cheeseburgers,
    but I guess those people exist.) Luckily, when you get to do what you love — and 
    you have the freedom freelancing affords — there is hardly any resentment for the work.</p>
    
    <p>When I’m not writing, I tend to be reading, as all the best writers are. 
    For pleasure, I gravitate toward biographies of European royalty and history books 
    (Erik Larson’s <em>In the Garden of Beasts</em> has stayed with me years after reading), 
    along with Internet articles ranging in topic from current events to feminism to 
    ponytail hacks. Oh, and I borrow my mom’s <em>Good Housekeeping</em> magazines, if only for 
    the advice columns on how to remove stains or tell a rude houseguest to hit the road.</p>
    
    <p>When I’m not reading, I am laughing at some witty comment my kiddo made, 
    whipping up something in the kitchen for my food-vacuum fiance (all noodles everything), 
    watching the latest <em>Game of Thrones</em> episode or taking my beagle Baratheon to the dog park 
    (so he can sniff every square inch and not socialize with any of the other dogs, of course).</p>
</div>

app/views/pages/contact.html.erb
<div id="contact" class="sectionDiv">
<div class="sectionTitle">Contact</div>
<hr class="sectionHR">

<p>If you would like to contact me, you can email me at:</p>

<p><h4>carajsuppa@gmail.com</h4></p>

<p>Ask questions (get answers!), request more samples or get in touch if 
you are interested in my writing and would like to put me to work for you.</p>

<p>You can find me on Linkedin at the link below:</p>
<a href="https://www.linkedin.com/in/cara-j-suppa-9b504625"><i class="fa fa-linkedin-square fa-5x"></i></a>

</div>

app/views/pages/home.html.erb
<div class="sectionDiv">
                        <p class="sectionTitle">Home</p>
                        <hr class="sectionHR">
                        <%= image_tag("caraErie.jpg", :id => "erieIMG", :class => "img-responsive") %>
                        <p>Welcome to the online portfolio for <strong>Cara J. Suppa</strong>, or as I know myself: that 
                        gal with the slavish devotion to word processors and iced coffee. 
                        I’m a freelance writer living and working out of Erie, PA, less than a mile from 
                        beautiful Lake Erie (pictured above at the Walnut Creek Marina — yes, that’s really 
                        Pennsylvania, give or take a few Instagram filters) and the incomparable Presque Isle State Park. 
                        Feel free to take a look around my site, and I hope you’ll take the time to read 
                        through my samples, versatile and award-winning (seriously!) as they are.</p>
                    </div>

app/views/pages/portfolio.html.erb
<div id="portfolio" class="sectionDiv">
<div class="sectionTitle">PORTFOLIO</div>
<hr class="sectionHR">

<div>
    <h4>Fiction:</h4>
    <p>“<em><a href="/for_sale.pdf">For Sale</a></em>” (a complete short story)</p>
    <p>Tentatively titled “<em><a href="/the_starling.pdf">The Starling</a></em>” (an excerpt from a longer piece)</p>
    <p><em>Ghostwriting samples available upon request.</em></p>
</div>

&nbsp;

<div>
    <h4>Personal Essays:</h4>
    <p>“<em><a href="/erosion.pdf">Erosion</a></em>”</p>
    <p>“<em><a href="/getting_ready.pdf">Getting Ready</a></em>”</p>
</div>

&nbsp;

<div>
    <h4>Content Examples:</h4>
    <p>“<em><a href="/five-of-the-latest-developments-in-the-world-of-nursing.pdf">Five of the Latest Developments in the World of Nursing</a></em>”</p>
    <p>“<em><a href="/money-wasting-car-myths.pdf">Money-wasting Car Myths</a></em>”</p>
    <p>“<em><a href="/six-funny-car-owner-stereotypes.pdf">Six Funny Car Owner Stereotypes</a></em>”</p>
    <p>“<em><a href="/the-three-biggest-threats-to-public-health.pdf">Three Biggest Threats To Public Health</a></em>”</p>
    <p>“<em><a href="/mylifelb24m3-5.pdf">How to be a Successful Couple on Facebook</a></em>”</p>
</div>

&nbsp;

<div>
    <h4>Two Highly Irreverent Movie Reviews (for my friend’s pop culture blog):</h4>
    <p><em><a href="http://www.theuselesscritic.com/2012/07/the-dark-knight-rises-review-two-ways.html">The Dark Knight Rises</a></em></p>
    <p><em><a href="http://www.theuselesscritic.com/2012/12/a-joint-jaunt-through-les-mis.html">Les Miserables</a></em></p>
</div> 

&nbsp;

</div>

app/views/pages/resume.html.erb
<div id="resume" class="sectionDiv">
<div class="sectionTitle">Resumé</div>
<hr class="sectionHR">
<p><h4>STRENGTHS:</h4></p>
<p><strong>Writing, Editing, Proofreading, Research, Web Savvy</strong></p>
<ul>
    <li>Superb knowledge and understanding of grammar, syntax, semantics, spelling and punctuation.</li>&nbsp;
    <li>Command of most writing styles, including AP Style and MLA.</li>&nbsp;
    <li>Exhaustive research capabilities online and in print.</li>&nbsp;
    <li>Fluent use of social media sites: Facebook, Twitter, Youtube, etc.</li>&nbsp;
</ul>



<div id="experience">
<h4>EXPERIENCE:</h4>
    <p><strong>Freelance content writer (May 2012-present)</strong></p>
        <p>Generates article topics, researches and creates accessible, 
         engaging content on a variety of topics while incorporating keywords 
         and maintaining AP style, with emphasis on meeting deadlines.</p>
         
    <p><strong>Freelance fiction writer (April 2011-present)</strong></p>
        <p>Creates stories up to 50,000 words in length while working with detailed 
         outlines, fleshing out characters and creating larger-than-life situations 
         aimed to titillate, resonate and entertain.</p>
    <p><strong>Copy editor, Edinboro University Spectator (August 2009-April 2010)</strong></p>
         <p>Perused news copy for errors in spelling, grammar and adherence to AP style 
         while fact-checking articles for accuracy.</p>
</div>&nbsp;
 
<h4>EDUCATION:</h4>
<strong>Bachelor of Arts, English Writing
Edinboro University of Pennsylvania, Edinboro, PA
Fall 2010, summa cum laude</strong>
<ul>
    <li>3.8 GPA overall; 3.9 GPA within major.</li>&nbsp;
    <li>Minor in history.</li>&nbsp;
    <li>Coursework in technical and business writing; creative nonfiction; fiction and poetry; and grammar and linguistics.</li>&nbsp;
    <li>Outstanding Departmental Senior for the 2010 school year.</li>&nbsp;
    <li>Recipient of Pfingstler English scholarship in 2010 and Frank LaBounty scholarship from 2008-2010.</li>&nbsp;
    <li>Member and vice president of Sigma Tau Delta, EUP’s English honors society from 2009-2010.</li>&nbsp;
</ul>
<em>References available upon request.</em>

</div>

app/views/partials/_footer.html.erb
</body>
</html>

app/views/partials/_header.html.erb
<!DOCTYPE html>
<html>
    <header>
        <title>
            Cara J. Suppa: The Online Writing Portfolio
        </title>
    </header>
<body> 
 
<div class="headContainer">
     <div id="headTitle">Cara J. Suppa: The Online Writing Portfolio</div>
          
            <span id="navbarLinks"><a href="/">Home</a></span>
            <span id="navbarLinks"><a href="/about">About</a></span>
            <span id="navbarLinks"><a href="/portfolio">Portfolio</a></span>
            <span id="navbarLinks"><a href="/resume">Resumé</a></span>
            <span id="navbarLinks"><a href="/contact">Contact</a></span>
            <span id="navbarLinks"><a href="/articles">Blog</a></span>
            
</div>

  <div id="blurb" class="sectionDiv">
     <%= image_tag("cara.jpg", :alt => "cara and dog") %>
    <p class="nameBlurb">Cara J. Suppa</p>
    <hr class="sectionHR">
    <p>Freelance writer, glorious/low-brow foodie and recent iPhone convert. 
    Witness my effort to rein in an almost debilitating tendency toward sarcasm 
    and self-deprecation.</p>
      
  </div>

app/views/users/new.html.erb
<div id="newUser" class="sectionDiv">
<div class="sectionTitle">Sign Up</div>
<hr class="sectionHR">

<% if @user.errors.any? %>
<ul>
    <h4>There were errors with your sign up:</h4>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
</ul>
<% end %>

<%= form_for @user do |f| %> 

    <div>
        Enter a Username:<%= f.text_field :username %>
    </div> <br>
    <div>
        Enter a Password: <%= f.password_field :password %> 
    </div><br>
    <div>
        <%= f.submit "Sign Up" %>
    </div>

<% end %> 

</div>